name: Initialize Cloudify Profile
author: Isaac Shabtay
description: Initializes a Cloudify CLI profile
branding:
  icon: cloud
  color: white
runs:
  using: docker
  image: docker://isaaccfy/cfy-ci:latest
  entrypoint: cfyci
  args:
    - init
