name: Initialize Cloudify Profile
author: Isaac Shabtay
description: Initializes a Cloudify CLI profile
branding:
  icon: cloud
  color: white
runs:
  using: docker
  image: docker://cloudifyplatform/cloudify-cli:6.3.0
  entrypoint: cfyci
  args:
    - init
